### ISSUE TITLE
改了帧率 还是卡顿

### ISSUE THREAD

**Issue by stevenliuit** [ALI1416/ScreenShare#1]
改了帧率后 拖动鼠标还是卡顿 大概fps是再3~8的样子 到不了60 fps那种

**Comment by ALI1416** [comment]
项目使用了单线程截取屏幕。
无法达到很高帧率。
本机使用的CPU为`i5-12500`，屏幕分辨率为`1920x1080`，帧率设置为`0`(最快)，使用地址`127.0.0.1`，最高可以达到`20`帧。
如果使用局域网传输，取决于路由器或交换机的最高速率，如果为`100M`交换机，最高可以达到`4`帧。

**Comment by stevenliuit** [comment]
感谢 我测试一下 感觉帧率还是达不到向日葵那种软件的

**Comment by ALI1416** [comment]
对的。
我使用过多线程来实现，测试最高可以达到`60`帧，但是软件容易崩溃，待我有空再研究下吧。

**Comment by stevenliuit** [comment]
> 对的。 我使用过多线程来实现，测试最高可以达到`60`帧，但是软件容易崩溃，待我有空再研究下吧。

我觉得局域网如果能达到多线程到30针 有可能会好吧

**Comment by ALI1416** [comment]
好的哈。
多谢建议，抽空我会改进一下的。

**Comment by stevenliuit** [comment]
> 好的哈。 多谢建议，抽空我会改进一下的。

网上看到了一个这个 https://github.com/pavlobu/deskreen
测试了一下 他把桌面串联成流了 然后打开看 一点不卡

**Comment by ALI1416** [comment]
大致看了一下，使用了FFmpeg，可以参考一下。
不过使用了跨平台框架Electron，体积过于庞大。

**Comment by ALI1416** [comment]
大致看了一下，使用了FFmpeg，可以参考一下。
不过使用了跨平台框架Electron，体积过于庞大。

**Comment by stevenliuit** [comment]
> 大致看了一下，使用了FFmpeg，可以参考一下。 不过使用了跨平台框架Electron，体积过于庞大。

我觉得不需要用Electron就行，只兼容windows就可以吧，毕竟打开是浏览器 应该没关系，ffmpeg只是编解码工具
